# Change these first
owner: INNARSSAC # Your GitHub organization or username, where this repository lives
repo: innarsupptime # The name of this repository

sites:
  - name: Comer al toque
    url: https://www.comeraltoque.com/
  - name: Sacrun SAC
    url: https://www.sacrun.com/
  - name: Sacrun SAC Revistas
    url: https://revista.sacrun.com/
  - name: INNARS
    url: https://www.innars.com
  - name: Google
    url: https://www.google.com
  - name: Discord
    url: https://discord.com/
    
assignees:
  - drandredev
  - Raul122-dev
  - DiegoPamo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.innars.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.innars.com/static/local/img/new_img1/INNARS_negro.png
  name: INNARS STATUS OF SERVICES
  introTitle: "Conoce el estado de nuestros servicios en caso exista una ocurrencia."
  introMessage: Nuestro equipo está monitoreando en **tiempo real** el estado de nuestros servidores y servicios.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
